sudo: false
language: python
python:
  - 2.7

env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.5

install:
  - pip install -q coverage Django==$DJANGO_VERSION

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
