sudo: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=2.2.8
  - DJANGO_VERSION=3.0

install:
  - pip install -q coverage Django==$DJANGO_VERSION

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  exclude:
    - python: 3.5
      env: DJANGO_VERSION=3.0
