sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.7

install:
  - pip install -q coverage six Django==$DJANGO_VERSION

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
