sudo: false
language: python
python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=2.2.8
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1

install:
  - pip install -q coverage Django==$DJANGO_VERSION

script: coverage run --source=. ./runtests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
