sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.8
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1

install:
  - pip install -q coverage six Django==$DJANGO_VERSION

script: coverage run --source=. ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0
    - python: 2.7
      env: DJANGO_VERSION=2.1
    - python: 3.4
      env: DJANGO_VERSION=2.1
  include:
    - python: 3.6
      env: DJANGO_VERSION=1.11.8
    - python: 3.6
      env: DJANGO_VERSION=2.0
    - python: 3.6
      env: DJANGO_VERSION=2.1
    - python: 3.5
      env: DJANGO_VERSION=2.2
    - python: 3.6
      env: DJANGO_VERSION=2.2
    - python: 3.5
      env: DJANGO_VERSION=3.0
    - python: 3.6
      env: DJANGO_VERSION=3.0
